DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME STRING NOT NULL,
    EMAIL STRING NOT NULL,
    PW_HASH STRING NOT NULL
);

DROP TABLE IF EXISTS FOLLOWER;
CREATE TABLE FOLLOWER(
    WHO_ID INTEGER,
    WHOM_ID INTEGER
);

DROP TABLE IF EXISTS MESSAGE;
CREATE TABLE MESSAGE(
    MESSAGE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTHOR_ID INTEGER NOT NULL,
    TEXT STRING NOT NULL,
    PUB_DATE INTEGER
);